def greeting():
    print("Hello from Phoenix!")


def collatz(seed):
    """
    Applies the Collatz Conjecture to a given seed number.

    Args:
        seed: A positive integer.

    Returns:
        A list containing the sequence of numbers generated by the Collatz Conjecture,
        starting with the seed.  Returns an empty list if the seed is not a positive integer.
    """
    if not isinstance(seed, int) or seed <= 0:
        return []

    sequence = [seed]
    current = seed

    while current != 1:
        if current % 2 == 0:
            current = current // 2
        else:
            current = 3 * current + 1
        sequence.append(current)

    return sequence


if __name__ == "__main__":
    greeting()

    # Example usage:
    seed_number = 17
    collatz_sequence = collatz(seed_number)

    if collatz_sequence:
        print(f"Collatz sequence for seed {seed_number}:")
        print(collatz_sequence)

    else:
        print("Invalid seed. Please provide a positive integer.")
